name = "ExprBuild"
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
JSON = "0.21"
Symbolics = "5.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
